;**************************************************************************
; SBM 2015. ESTRUCTURA BÁSICA DE UN PROGRAMA EN ENSAMBLADOR
; AUTORES: JOSE IGNACIO GOMEZ GARCIA, OSCAR GOMEZ BORZDYNSKI
; PAREJA 14
;**************************************************************************
; DEFINICION DEL SEGMENTO DE DATOS
DATOS SEGMENT
;-- rellenar con los datos solicitados
DATOS ENDS
;**************************************************************************
; DEFINICION DEL SEGMENTO DE PILA
PILA SEGMENT STACK "STACK"
	DB 40H DUP (0) ;ejemplo de inicialización, 64 bytes inicializados a 0
PILA ENDS
;**************************************************************************
; DEFINICION DEL SEGMENTO EXTRA
EXTRA SEGMENT
	RESULT DW 0,0 ;ejemplo de inicialización. 2 PALABRAS (4 BYTES)
EXTRA ENDS
;**************************************************************************
; DEFINICION DEL SEGMENTO DE CODIGO
CODE SEGMENT
	ASSUME CS: CODE, DS: DATOS, ES: EXTRA, SS: PILA
; COMIENZO DEL PROCEDIMIENTO PRINCIPAL
INICIO PROC
	; INICIALIZA LOS REGISTROS DE SEGMENTO CON SU VALOR
	MOV AX, DATOS
	MOV DS, AX
	MOV AX, PILA
	MOV SS, AX
	MOV AX, EXTRA
	MOV ES, AX
	MOV SP, 64 ; CARGA EL PUNTERO DE PILA CON EL VALOR MAS ALTO
	; FIN DE LAS INICIALIZACIONES
	; COMIENZO DEL PROGRAMA
	MOV AX, 15H ; CARGAMOS 15H EN AX
	MOV BX, 0BBH ; CARGAMOS BBH EN BX
	MOV CX, 3412H ; CARGAMOS 3412H EN CX
	MOV DX, CX ; CARGAMOS EL CONTENIDO DE CX EN DX
	
	MOV AX, 6000H ; CARGAMOS 6000H EN AX PARA PASARLO A DS
	MOV DS, AX
	MOV BX, 5636H ; CARGAMOS LA DIRECCION EN AX PARA PODER REFERENCIARLA
	MOV BX, [BX] ; CARGAMOS LA POSICION [60000+5636 H] EN BX (BL <- [65636H] Y BH <- [65637H])
	
	MOV AX, 5000H ; CARGAMOS 5000H EN AX PARA PASARSELO A DS
	MOV DS, AX
	MOV BX, 5H
	MOV [BX], CH ; CARGAMOS EN LA POSICION [50005H] EL CONTENIDO DE CH

	MOV AX, [DI] ; CARGAMOS EN AX EL CONTENIDO DE LA POSICION APUNTADA POR DI

	MOV BX, [BP]+10 ; CARGAMOS EN BX EL CONTENIDO DE LA DIRECCION QUE ESTA 10B POR ENCIMA DE BP
	; FIN DEL PROGRAMA
	MOV AX, 4C00H
	INT 21H
INICIO ENDP
; FIN DEL SEGMENTO DE CODIGO
CODE ENDS
; FIN DEL PROGRAMA INDICANDO DONDE COMIENZA LA EJECUCION
END INICIO