;**************************************************************************
; SBM 2015. ESTRUCTURA BÁSICA DE UN PROGRAMA EN ENSAMBLADOR
; AUTORES: JOSE IGNACIO GOMEZ GARCIA, OSCAR GOMEZ BORZDYNSKI
; PAREJA 14
;**************************************************************************
; DEFINICION DEL SEGMENTO DE DATOS
DATOS SEGMENT

CONTADOR DB 0 ; CREAMOS LA VARIABLE CONTADOR CON 1B, INICIALIZADA A 0
TOME DW 0CAFEH ; VARIABLE TOME DE 2B INICIALIZADA A CAFEH
TABLA100 DB 100 DUP (0) ; VARIABLE TABLA100 DE 100B INICIALIZADOS A 0

ERROR1 DB "Atencion: Entrada de datos incorrecta.$"

DATOS ENDS
;**************************************************************************
; DEFINICION DEL SEGMENTO DE PILA
PILA SEGMENT STACK "STACK"
	DB 40H DUP (0) ;ejemplo de inicialización, 64 bytes inicializados a 0
PILA ENDS
;**************************************************************************
; DEFINICION DEL SEGMENTO EXTRA
EXTRA SEGMENT
	RESULT DW 0,0 ;ejemplo de inicialización. 2 PALABRAS (4 BYTES)
EXTRA ENDS
;**************************************************************************
; DEFINICION DEL SEGMENTO DE CODIGO
CODE SEGMENT
	ASSUME CS: CODE, DS: DATOS, ES: EXTRA, SS: PILA
; COMIENZO DEL PROCEDIMIENTO PRINCIPAL
INICIO PROC
	; INICIALIZA LOS REGISTROS DE SEGMENTO CON SU VALOR
	MOV AX, DATOS
	MOV DS, AX
	MOV AX, PILA
	MOV SS, AX
	MOV AX, EXTRA
	MOV ES, AX
	MOV SP, 64 ; CARGA EL PUNTERO DE PILA CON EL VALOR MAS ALTO
	; FIN DE LAS INICIALIZACIONES
	; COMIENZO DEL PROGRAMA
	MOV AH, ERROR1[5] ; CARGAMOS EN AH EL SEXTO CARACTER DE ERROR1
	MOV TABLA100[63H], AH ; LO GUARDAMOS EN LA POSICION 63H DE TABLA100

	MOV AX, TOME ; CARGAMOS EN AX LOS DOS BYTES DE TOME
	MOV TABLA100[23H], AH ; GUARDAMOS EN LA POSCION 23H DE LA TABLA EL BYTE MAS SIGNIFICATIVO DE TOME 
	MOV TABLA100[24H], AL ; AHORA GUARDAMOS EL MENOS SIGNIFICATIVO EN LA POSICION SIGUIENTE

	MOV CONTADOR, AH ; GUARDAMOS EL BYTE MAS SIGNIFICATIVO EN EL CONTADOR


	; FIN DEL PROGRAMA
	MOV AX, 4C00H
	INT 21H
INICIO ENDP
; FIN DEL SEGMENTO DE CODIGO
CODE ENDS
; FIN DEL PROGRAMA INDICANDO DONDE COMIENZA LA EJECUCION
END INICIO