######################################################################
##
## Filename: processor_tb.udo
## Created on: Tue Sep 26 10:03:42 Hora de verano romance 2017
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
