# all: pract2b.exe prueba.exe
all: prueba.exe

# pract2b.exe: pract2b.obj
# 	tlink /v pract2b

# pract2b.obj: pract2b.asm
# 	tasm /zi pract2b.asm

prueba.exe: prueba.obj
	tlink /v prueba

prueba.obj: prueba.asm
	tasm /zi prueba.asm